### ISSUE TITLE
Update extensions to match standards

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-extension-issues#42]
- React 18 support, node 18
- Webpack 5 (and general dependencies update)
- A11y (at least testing on each PR)
- Linting - bump to version 8

Extensions to update:
- [x] patternfly/patternfly-quickstarts#235
- [x] patternfly/react-catalog-view#36
- [x] patternfly/react-log-viewer#21
- [x] patternfly/react-console#31
- [x] patternfly/react-user-feedback#28
- [ ] patternfly/react-component-groups#16
