### ISSUE TITLE
Update extensions to consume PF alpha omega release

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-extension-issues#59]
```[tasklist]
### Tasks
- [x] Update topology to PF Alpha Omega
- [x] Update console to PF Alpha Omega
- [x] Update log viewer to PF alpha Omega
- [x] Update quick starts to PF alpha omega
- [x] Update virtualize extension to PF alpha omega
- [x] Update user feedback to PF alpha omega
- [x] Update catalog view to PF alpha omega
- [ ] Update PF extension seed ot PF alpha omega
- [x] Update react seed to PF alpha omega
```
